import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <header className="flex flex-wrap sm:flex-nowrap justify-between items-center px-4 pt-6 pb-3 sm:py-4 sm:px-6 gap-3 sm:gap-4 border-b border-stone-200/40 dark:border-stone-900/40 bg-white/60 dark:bg-black/60 backdrop-blur-md sticky top-0 z-40">
            <h1 className="text-base sm:text-xl uppercase tracking-[0.18em] sm:tracking-[0.25em] text-[#8f6d3d] dark:text-[#c4a06d] font-semibold shrink-0">
              Backstage Chat.me
            </h1>
            <div className="flex items-center gap-2 sm:gap-3">
              <Show when="signed-out">
                <SignInButton>
                  <button className="border border-zinc-300 dark:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-900 text-zinc-900 dark:text-zinc-100 rounded-full font-medium text-xs sm:text-sm h-9 sm:h-10 px-3.5 sm:px-4 cursor-pointer whitespace-nowrap">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#8f6d3d] hover:bg-[#7a5c32] text-white rounded-full font-medium text-xs sm:text-sm h-9 sm:h-10 px-3.5 sm:px-4 transition-all duration-200 active:scale-95 cursor-pointer shadow-sm hover:shadow-md whitespace-nowrap">
                    Sign Up
                  </button>
                </SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserButton />
              </Show>
            </div>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}